### ISSUE TITLE
Allow specifying allow list of trusted runner labels

### ISSUE THREAD

**Issue by fproulx-boostsecurity** [boostsecurityio/poutine#155]
Let's say one has custom GitHub hosted runners they would have other labels, we need to allow list those
The self hosted runner rule should honor this list in addition to hardcoded regex

**Comment by fproulx-boostsecurity** [comment]
Draft of config file
```
include:
- path: .poutine
ignoreForks: true
rulesConfig:
  pr_runs_on_self_hosted:
    trusted_runner_labels: [ "my-paid-hosted-runner" ]
```
